### ISSUE TITLE
Create contrib payment provider by default

### ISSUE THREAD

**Issue by bjarnef** [vendrhub/vendr-templates#2]
When using payment provider template `dotnet new vendr-payment-provider -n Braintree` it will create to Umbraco package as following:  
`<name>Vendr.PaymentProviders.Braintree</name>`.

However for contrib payment providers it should be this instead:

`<name>Vendr.Contrib.PaymentProviders.Braintree</name>`.

https://github.com/vendrhub/vendr-templates#example-to-start-a-new-payment-provider-project

![image](https://user-images.githubusercontent.com/2919859/137730113-260f1104-79c6-4833-978c-66303188c4d4.png)

Although https://our.umbraco.org works and redirect, I would probably just use https://our.umbraco.com which is now the primary domain.

**Comment by mattbrailsford** [comment]
Good spot. Fixed in commit 7255ab02f7ce0ab6a2d7d4e30b409f4554c72310

**Comment by bjarnef** [comment]
@mattbrailsford great. Should we also use https://our.umbraco.com instead of https://our.umbraco.org since that's the primary domain. https://our.umbraco.org will probably still redirect to https://our.umbraco.com for a while or as long Umbraco wants to keep the `.org` domain 😁

**Comment by mattbrailsford** [comment]
Lol, shows how much attention I pay, didn't even know Umbraco changed it 😂

Updated too 👍
